Feature/snackbar
peaksoft-school/billingual-js8 pull request #17
Opened 2023-04-13 07:20 UTC by Alievamadina

2023-04-13 07:55 UTC, AziatAbd requested changes

2023-04-13 07:55 UTC, AziatAbd commented on src/components/UI/snackbar/Snackbar.jsx
> +         <Button onClick={notify}>Success!</Button>
Button калып кетиптир

2023-04-13 12:56 UTC, songhee24 requested changes

2023-04-13 12:56 UTC, songhee24 commented on src/index.js
> -   <React.StrictMode>
зачем убрали  <React.StrictMode>?

2023-04-13 12:56 UTC, songhee24 commented on src/components/UI/snackbar/Snackbar.jsx
> +      notify()
нет так не стоит делать ваш тоаст должен вызываться внутри какой то функции а не в рендере

2023-04-14 07:20 UTC, songhee24 approved these changes

2023-04-14 07:20 UTC, merged