landing page part 2
peaksoft-school/billingual-js8 pull request #18
Opened 2023-04-13 14:22 UTC by Zarlykova

2023-04-13 18:53 UTC, AnarbekIshembekUulu commented
Background ак болуп калыптыр.

2023-04-14 04:49 UTC, AziatAbd requested changes

2023-04-14 04:49 UTC, AziatAbd commented on src/assets/icons/Vector 2.svg
название иконок должны начинаться с маленькой буквы и логическое название желательно

2023-04-14 04:49 UTC, AziatAbd commented on src/assets/icons/Group 4376.svg
тоже самое

2023-04-14 07:30 UTC, songhee24 requested changes

2023-04-14 07:30 UTC, songhee24 commented on src/components/landing-page/UsefulVideos.jsx
> +               {videos.map((item) => (
может через you tube рандомные видео поставите ? и чтобы  внутри карточки можно было бы посмотреть

2023-04-14 07:30 UTC, songhee24 commented on src/components/landing-page/UsefulVideos.jsx
> +               {videos.map((item) => (
нажав на плей

2023-04-17 07:59 UTC, songhee24 requested changes

2023-04-17 07:59 UTC, songhee24 commented on src/components/landing-page/LearnMore.jsx
> +import { ReactComponent as Icon } from '../../assets/icons/roadmap.svg'
ReactComponent as Icon может называть тоже правильно стоит ? 
`import { ReactComponent as Roadmap } from '../../assets/icons/roadmap.svg'`

2023-04-17 07:59 UTC, songhee24 commented on src/components/landing-page/UsefulVideos.jsx
> +                  const divRef = createRef(null)
ref ни к чему можно убрать здесь

2023-04-17 07:59 UTC, songhee24 commented on src/components/landing-page/UsefulVideos.jsx
> +                  const openModel = () => {
плюс функцию создайте снаружи map а не внутри

2023-04-17 07:59 UTC, songhee24 commented on src/components/landing-page/UsefulVideos.jsx
> +                     divRef.current.classList.remove('video')
тоже не понимаю зачем и для чего вы решили это добавить

2023-04-18 10:56 UTC, songhee24 approved these changes

2023-04-18 10:56 UTC, merged