Feature/drag and drop
peaksoft-school/billingual-js8 pull request #20
Opened 2023-04-15 10:14 UTC by AziatAbd

2023-04-18 06:33 UTC, Alievamadina commented
good

2023-04-18 06:44 UTC, lil1it requested changes

2023-04-18 06:44 UTC, lil1it commented on src/components/UI/drag-and-drop/DragAndDrop.jsx
> +      console.log('start', item)
убрал бы console.log

2023-04-19 05:05 UTC, Kamchybekk commented
Uploading Screen Recording 2023-04-19 at 11.04.06.mov…

иштебейт экен

2023-04-19 05:07 UTC, Kamchybekk commented
![Uploading Screen Shot 2023-04-19 at 11.07.42.png…]()

2023-04-19 05:09 UTC, Kamchybekk commented
![Screen Shot 2023-04-19 at 11 09 41](https://user-images.githubusercontent.com/115062260/232972452-a0d2bbc4-17a7-43b0-89a7-b9941fe064d2.png)

басып алып барсам иштеген жок

2023-04-19 05:12 UTC, Kamchybekk commented
Бул ui компонента эмес

2023-04-19 11:40 UTC, merged