Feature/dropdown
peaksoft-school/billingual-js8 pull request #21
Opened 2023-04-18 06:29 UTC by Alievamadina

2023-04-18 07:11 UTC, AziatAbd requested changes

2023-04-18 07:11 UTC, AziatAbd commented on src/components/UI/dropdowns/Dropdowns.jsx
> +      changeSelect(typeof value === 'string' ? value.split(',') : value)
onChange функция должна передаваться через пропс

2023-04-18 07:11 UTC, AziatAbd commented on src/components/UI/dropdowns/Dropdowns.jsx
> +         </MenuItem>
можно убрать она лишняя

2023-04-18 07:11 UTC, AziatAbd commented on src/components/UI/dropdowns/Dropdowns.jsx
> +   '&:hover': {
добавьте borderRadius

2023-04-18 10:48 UTC, songhee24 requested changes

2023-04-18 10:48 UTC, songhee24 commented on src/components/UI/dropdowns/Dropdowns.jsx
> +   fontFamily: 'DINNextRoundedLTW01-Regular',
'DINNextRoundedLTW01-Regular', что это ?

2023-04-19 06:30 UTC, Alievamadina commented on src/components/UI/dropdowns/Dropdowns.jsx
> +   fontFamily: 'DINNextRoundedLTW01-Regular',
Фигмада fontFamily  ушундай экен

2023-04-19 06:44 UTC, songhee24 approved these changes

2023-04-19 06:46 UTC, merged