feature/store
peaksoft-school/billingual-js8 pull request #26
Opened 2023-04-26 11:19 UTC by AnarbekIshembekUulu

2023-04-26 11:30 UTC, AziatAbd requested changes

2023-04-26 11:30 UTC, AziatAbd commented on src/store/index.js
> +export const store = createStore(rootReducer, applyMiddleware(thunk))
configureStore колдонун

2023-04-26 11:30 UTC, AziatAbd commented on package.json
> +    "redux-thunk": "^2.4.2",
thunk кереги жок

2023-04-28 05:45 UTC, Kamchybekk commented on src/redux/auth/auth.slice.js
> +const initialState = {}
authSlice initialState эмнеге пустой?

2023-05-01 08:00 UTC, songhee24 approved these changes

2023-05-01 08:00 UTC, merged