signin-signup page
peaksoft-school/billingual-js8 pull request #27
Opened 2023-04-27 10:23 UTC by Zarlykova

2023-04-27 10:55 UTC, AziatAbd approved these changes

2023-04-28 14:29 UTC, songhee24 requested changes

2023-04-28 14:29 UTC, songhee24 commented on src/containers/public/SignupPage.jsx
> +                  (errors.email,
давайте проверки вынесем в какую то переменную а то читать не удобно

2023-05-01 07:19 UTC, songhee24 approved these changes

2023-05-01 07:19 UTC, merged