Feature/create admin test
peaksoft-school/billingual-js8 pull request #30
Opened 2023-05-09 11:18 UTC by AnarbekIshembekUulu

2023-05-09 13:04 UTC, AziatAbd requested changes

2023-05-09 13:04 UTC, AziatAbd commented on src/components/header/Header.jsx
Наоборот, svg, img файлдар кичинекей тамганан башталыш керек

2023-05-09 13:04 UTC, AziatAbd commented on src/components/landing-page/Footer.jsx
> +import { ReactComponent as Instagram } from '../../assets/icons/Instagram.svg'
тоже самое

2023-05-09 13:04 UTC, AziatAbd commented on src/components/landing-page/Partners.jsx
> +import Lidea from '../../assets/icons/Lidea.svg'
здесь тоже

2023-05-09 13:04 UTC, AziatAbd commented on src/components/landing-page/SecondSlider.jsx
> +import { ReactComponent as ActivePagination } from '../../assets/icons/ActivePagination.svg'
и здесь

2023-05-09 13:04 UTC, AziatAbd commented on src/components/landing-page/landingSlider/Slider.jsx
> +import { ReactComponent as ActivePagination } from '../../../assets/icons/ActivePagination.svg'
аналогично

2023-05-09 13:04 UTC, AziatAbd commented on src/containers/admin/pages/AdminTest.jsx
> +import { ReactComponent as DeleteIcon } from '../../../assets/icons/DeletedIcon.svg'
и тут

2023-05-09 13:04 UTC, AziatAbd commented on src/containers/admin/pages/adminCreateTestRealEnglishWords/DeleteModal.jsx
> +const ModalkaDelete = ({ isOpenModal, openModal }) => {
Дайте нормальное название, пожалуйста.

2023-05-09 13:04 UTC, AziatAbd commented on src/containers/admin/pages/adminCreateTestRealEnglishWords/DeleteModal.jsx
> +               <DeleteButton variant="contained">Delete</DeleteButton>
через пропс какая-то функция должна прийти для удаления

2023-05-09 13:05 UTC, AziatAbd commented on src/routes/admin/AdminRoute.jsx
> +         <AdminCreateTest />
удалите здесь и добавьте в Route

2023-05-22 05:08 UTC, Kamchybekk commented
![Screen Shot 2023-05-22 at 11 07 31](https://github.com/peaksoft-school/billingual-js8/assets/115062260/43070233-6bba-4a06-b3a3-284be325f049)
 
 каждый refresh сайын toasfity чыгып жатат кереги жок.Update test после post либо put тест болгондо эле чыксын

2023-05-23 06:14 UTC, merged