Feature/admin test crud
peaksoft-school/billingual-js8 pull request #31
Opened 2023-05-11 11:52 UTC by AziatAbd

2023-05-12 01:04 UTC, AnarbekIshembekUulu approved these changes

2023-05-15 08:28 UTC, songhee24 requested changes

2023-05-15 08:28 UTC, songhee24 commented on src/components/landing-page/Footer.jsx
>  import { ReactComponent as PlusIcon } from '../../assets/icons/plus.svg'
да импорты исправили но не забывайте сам файл тоже менять с моей стороны потом ошибки импорта мне обратно приходится их большими писать

2023-05-15 08:28 UTC, songhee24 commented on src/containers/admin/pages/test/AdminTest.jsx
> +
почему ни один запрос не обрабатывает ошибки ?

2023-05-15 08:28 UTC, songhee24 commented on src/containers/admin/pages/test/CreateTest.jsx
> +      if (state) {
нужно более комплексная проверка

2023-05-15 08:28 UTC, songhee24 commented on src/containers/admin/pages/test/CreateTest.jsx
> +               {state ? null : (
тут тоже

2023-05-15 08:28 UTC, songhee24 commented on src/containers/admin/pages/test/Questions.jsx
> +                        {test.questions.map((question, i) => (
проверка массива

2023-05-15 12:13 UTC, songhee24 requested changes

2023-05-15 12:13 UTC, songhee24 commented on src/containers/admin/pages/test/AdminTest.jsx
> +         dispatch(getTests())
разумно в этой ситуации давать в качестве параметров notify('error', 'Test', 'Failed to get tests') вашему методу  dispatch(getTests())

2023-05-15 12:13 UTC, songhee24 commented on src/containers/admin/pages/test/AdminTest.jsx
> +         notify('success', 'Test', 'Delete test')
тут тоже самое

2023-05-15 12:13 UTC, songhee24 commented on src/containers/admin/pages/test/Questions.jsx
> +      const { data } = await getTestById(testId)
try catch

2023-05-16 09:37 UTC, merged