Feature/type what you hear
peaksoft-school/billingual-js8 pull request #35
Opened 2023-05-24 11:10 UTC by lil1it

2023-05-24 11:13 UTC, AziatAbd approved these changes

2023-05-24 11:22 UTC, lil1it commented
approved

2023-05-25 14:10 UTC, songhee24 requested changes

2023-05-25 14:10 UTC, songhee24 commented on src/containers/admin/pages/adminCreateTestRealEnglishWords/type/TypeWhatHear.jsx
> +            <p>{audioUrl ? audioName : 'File_name_of_the_audio_file.mp3'}</p>
File_name_of_the_audio_file.mp место этого null или file name not found

2023-05-25 14:10 UTC, songhee24 commented on src/containers/admin/pages/adminCreateTestRealEnglishWords/type/TypeWhatHear.jsx
> +         navigate('/admin/test')
если происходит navigate а за ним асинхронный запрос обязательно нужно обрабатывать ошибки и еще ждать пока не закончится запрос

2023-05-29 11:15 UTC, songhee24 approved these changes

2023-05-31 04:59 UTC, merged