Landing/page/part 1
peaksoft-school/billingual-js8 pull request #8
Opened 2023-04-09 02:15 UTC by AnarbekIshembekUulu

2023-04-09 08:29 UTC, AziatAbd requested changes
добавьте в начало названии ветки feature/yourBranchName

2023-04-09 08:29 UTC, AziatAbd commented on src/components/landing-page/InfoSection.jsx
> +         </OurTeam>
Рекомендую использовать массив, вместо того чтобы рендерить их вручную

2023-04-09 08:29 UTC, AziatAbd commented on src/components/landing-page/InfoSection.jsx
> +            </Img1DivThird>
здесь тоже можно использовать массив и мапать его

2023-04-11 10:02 UTC, songhee24 requested changes

2023-04-11 10:02 UTC, songhee24 commented on src/components/landing-page/InfoSection.jsx
> +                     {elem.id === 1 && <OurTeamImage src={elem.img} />}
это так не пойдет э что тут такое ? 
если нужно менять картинки то посмотри в дизайне можно по алгоритму 
if(index % 2 == 0) {}

2023-04-11 10:02 UTC, songhee24 commented on src/assets/images/Group 4264.png
img компонента эмес зачем баш тамга менен жазылган

2023-04-11 10:02 UTC, songhee24 commented on src/components/landing-page/LandingPageSectionOne.jsx
> +const EnglishProficiency = styled('h3')(() => ({
<img width="671" alt="Screenshot 2023-04-11 at 16 00 07" src="https://user-images.githubusercontent.com/44497623/231127301-bd369330-e782-4a7d-bf4b-c9acd4210d72.png">
карасанчы дизайнда font family 
анан сеники 
<img width="613" alt="Screenshot 2023-04-11 at 16 02 14" src="https://user-images.githubusercontent.com/44497623/231127430-fdea1531-dd74-4867-9d05-938187fa7f6e.png">

2023-04-13 08:01 UTC, songhee24 approved these changes

2023-04-13 08:01 UTC, merged