Feature/slider and footer
peaksoft-school/billingual-js8 pull request #9
Opened 2023-04-09 08:09 UTC by AziatAbd

2023-04-10 08:10 UTC, Alievamadina commented
Сонун👍

2023-04-10 08:20 UTC, AnarbekIshembekUulu commented on src/components/landing-page/SecondSlider.jsx
> +})
Ошибок или недочетов не нашел.

2023-04-11 10:18 UTC, songhee24 requested changes

2023-04-11 10:18 UTC, songhee24 commented on src/assets/icons/ActivePagination.svg
зачем с заглавной буквой ? это не компонента

2023-04-11 10:18 UTC, songhee24 commented on src/components/landing-page/SecondSlider.jsx
> +import Avatar1 from '../../assets/images/Avatar1.jpg'
тоже самое фотки нужно с маленькой буквой

2023-04-11 10:18 UTC, songhee24 commented on src/components/landing-page/SecondSlider.jsx
> +   return (
все в принципе хорошо смущает только одна деталь 

<img width="355" alt="Screenshot 2023-04-11 at 16 18 17" src="https://user-images.githubusercontent.com/44497623/231131427-ff2be21f-21af-4451-8df2-69790711930f.png">

2023-04-11 12:32 UTC, songhee24 approved these changes

2023-04-11 12:32 UTC, merged